version: '2'

tasks:
  run:
    cmds:
      - ./go-todo-app

  build-server:
    cmds: go build
      ignore_error: true
    sources:
      - public/**/*

  watch-build:
    cmds:
      - cd ./client; npm run watch

  build-client:
    cmds:
      - cd ./client; npm run build
